---
title: "WIP Assessing bias corrected data"
author: "Ruth C E Bowyer"
output: 
  github_document:
    keep_html: true
  html_document:
    theme: cosmo
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    df_print: paged
  date: "`r format(Sys.Date())`"
---

```{r libs and setup, message=FALSE, warning=F}
rm(list=ls())

knitr::opts_knit$set(root.dir="/Volumes/vmfileshare/ClimateData/")

library(terra)
library(sp)
library(exactextractr)

dd <- "/Volumes/vmfileshare/ClimateData/"

```


## **0. About**

Assessing the bias correction applied using the ```cmethods``` package. 

## **0. Raw data**

Comparing to the 'Raw' (but reprojecte CPM data) 

```{r load raw data}
# Read in as list of quantile mapping data
## Each decade is seperated out - but potential should we brick these together?
p <- paste0(dd, "Reprojected/UKCP2.2/tasmax/01/latest/")
files <- list.files(p)

raw.files <- files[!grepl("aux.xml", files)]
raw.files.p <- paste0(p, raw.files)
raw.dat <- lapply(raw.files.p, rast) 

#Crop to Scotland extent 
scot <- vect("~/Library/CloudStorage/OneDrive-TheAlanTuringInstitute/CLIM-RECAL/clim-recal/data/Scotland/Scotland.bbox.shp")

raw.dat_c <- lapply(raw.dat, function(i){ crop(i, scot) })

raw.dat_r <- rast(raw.dat_c)
```



##**1. Bias corrected data **

Load and check files 

```{r load data 1}

# Each method is a sep file per decade 
# Create a character vector listing the methods 

p <- paste0(dd, "Debiased/tasmax/")
f <- list.files(p)
i <- c("debiased_delta_method_result", "debiased_linear_scaling_result", "debiased_quantile_delta_mapping", "debiased_quantile_mapping", "debiased_variance_scaling")

# Returns a list of stacked rasters (one for each method) 
debaised_data <- lapply(i, function(x){
  files <- f[grepl(x, f)]
  files.p <- paste0(p, files)
  #Reads in as list of Rasters 
  dat <- lapply(files.p, rast) 
  #Load all together so one raster per method
  files.r <- rast(dat)
})

nlyr(qm.files.r) #144000 - 40 x 12 x 30 day months
```

## **2. Assessing the bias correction methods**

### **2a. Time series**

Check the time series over the whole dataset makes sense

```{r}

```



