version: "3.8"

services:

  jupyter:
    build:
      context: .
      dockerfile: ./compose/jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan:rw
      - /mnt/vmfileshare:/mnt/vmfileshare:rw

  docs:
    build:
      context: .
      dockerfile: ./compose/docs/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/home/jovyan:rw

  rstudio:
    build:
      context: .
      dockerfile: ./compose/rstudio/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio:rw
