services:

  jupyter:
    build:
      context: .
      dockerfile: ./compose/jupyter/Dockerfile
    ports:
      - "8888:8888"
    # user: root
    environment:
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/home/jovyan:rw
      - /mnt/vmfileshare:/mnt/vmfileshare:rw

  docs:
    build:
      context: .
      dockerfile: ./compose/docs/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/home/jovyan:rw

  rstudio:
    build:
      context: .
      dockerfile: ./compose/rstudio/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio:rw
