---
title: "Quantile Mapping across three cities"
author: "Ruth C E Bowyer"
date: "`r format(Sys.Date())`"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 0. About

Testing `Qmap` for the 3 cities 

```{r libraries dd}
rm(list=ls())

library(qmap)
library(terra)
library(tidyverse) 
library(doParallel)

dd <- "/mnt/vmfileshare/ClimateData/"

```

## 1. Pre-processing

Qmap uses df as inpt so below CPM data is loaded and converted to df

```{r cpm hads processing}

cities <- c("London", "Manchester", "Glasgow")

#file locations for cropped versions of CPM and updated hads data
fps <- c(paste0(dd, "Cropped/three.cities/CPM/"),
            paste0(dd, "Cropped/three.cities/Hads.updated360/"))

x <- paste0(fps, rep(cities, 2))

#Run the conversion to df in parallel 
cores <- detectCores()
cl <- makeCluster(cores[1]-1)
registerDoParallel(cl)

    foreach(x = x, 
         .packages = c("terra", "tidyverse"),
             .errorhandling = 'pass') %dopar% { 

      fp <- paste0(x, "/")
      files <- list.files(fp)
      files.paths <- paste0(fp, files)

      # Load and to df
      dfL <- lapply(files.paths, function(i){
          r <- rast(i)
          rdf <- as.data.frame(r, xy=T) 
          return(rdf)
        }) 
  
        names(dfL) <- files
        
        #assign a nice name for easy referencing
        obj.name <- gsub("/mnt/vmfileshare/ClimateData/Cropped/three.cities/CPM/", "cpm.dfL.", x)
        obj.name <- gsub("/mnt/vmfileshare/ClimateData/Cropped/three.cities/Hads.updated360/", "obs.dfL.", obj.name)
        
        assign(obj.name, dfL, envir=.GlobalEnv)
  
             } 

 stopCluster(cl) 
  gc()
  
  
```

## 2. Apply bias correction by variable/run 

The called function was written to apply the following models:


```{r}

source("/home/dyme/Desktop/clim-recal/clim-recal/R/bias-correction-methods/apply_qmapQuant_to_crpd_df_fn.R")

var <- c("tasmax", "tasmin", "pr")
Runs <-c("05", "06", "07", "08")

lapply(cities, function(x){
  apply_qmap_to_cropped_dfL(region=x, var=var, Runs = Runs)})


```

